site:
  title: Apache Solr Reference Guide
  url: https://solr.apache.org/guide
  start_page: solr::index.adoc
content:
  sources:
#  - url: https://github.com/apache/solr
#    branches: jira/solr-15556-antora
#    start_path: solr/solr-ref-guide
#    edit_url: '{web_url}/tree/{refname}/{path}'
  - url: ../../
    branches: HEAD
    start_path: solr/solr-ref-guide
ui:
  bundle:
    url: https://nightlies.apache.org/solr/draft-guides/ui-bundle.zip
    snapshot: true
output:
  clean: true
  dir: ./build
asciidoc:
  attributes:
    stem:
