# This workflow warns of PRs that have had no activity for a specified amount of time.
#
# For more information, see https://github.com/actions/stale
name: Mark stale pull requests

on:
  # Run every day at 00:00 UTC
  schedule:
    - cron: '0 0 * * *'
  # Or run on demand
  workflow_dispatch:

jobs:
  stale:
    if: github.repository == 'apache/solr'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: write
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          days-before-pr-stale: 60
          days-before-issue-stale: -1   # we don't use issues
          days-before-close: -1         # don't close stale PRs/issues
          exempt-draft-pr: true         # don't mark draft PRs as stale
          stale-pr-label: "stale"       # label to use when marking as stale

          stale-pr-message: >
            This PR has had no activity for 60 days and is now labeled as stale. 
            Any new activity or converting it to draft will remove the stale label. 
            To attract more reviewers, tag someone or notify the dev@solr.apache.org mailing list. 
            Thank you for your contribution!

          operations-per-run: 100       # operations budget
